version: "3.7"
services:
  app:
    build:
      args:
        user: cilsy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: vuln
    container_name: vuln-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - vuln-net
  db:
    image: mysql/mysql-server:8.0
    container_name: vuln-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - vuln-net
  nginx:
    image: nginx:alpine
    container_name: vuln-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - vuln-net
networks:
  vuln-net:
    driver: bridge